def get_ps_layout():
    '''
        signals are abstracted from xilinx unisim library:
            <Vivado_Install_Dir>/data/vhdl/src/unisims/primitive/PS7.vhd
    '''
    ports = [
        ("DMA0DATYPE",                  2,  "output"),
        ("DMA0DAVALID",                 1,  "output"),
        ("DMA0DRREADY",                 1,  "output"),
        ("DMA0RSTN",                    1,  "output"),
        ("DMA1DATYPE",                  2,  "output"),
        ("DMA1DAVALID",                 1,  "output"),
        ("DMA1DRREADY",                 1,  "output"),
        ("DMA1RSTN",                    1,  "output"),
        ("DMA2DATYPE",                  2,  "output"),
        ("DMA2DAVALID",                 1,  "output"),
        ("DMA2DRREADY",                 1,  "output"),
        ("DMA2RSTN",                    1,  "output"),
        ("DMA3DATYPE",                  2,  "output"),
        ("DMA3DAVALID",                 1,  "output"),
        ("DMA3DRREADY",                 1,  "output"),
        ("DMA3RSTN",                    1,  "output"),
        ("EMIOCAN0PHYTX",               1,  "output"),
        ("EMIOCAN1PHYTX",               1,  "output"),
        ("EMIOENET0GMIITXD",            8,  "output"),
        ("EMIOENET0GMIITXEN",           1,  "output"),
        ("EMIOENET0GMIITXER",           1,  "output"),
        ("EMIOENET0MDIOMDC",            1,  "output"),
        ("EMIOENET0MDIOO",              1,  "output"),
        ("EMIOENET0MDIOTN",             1,  "output"),
        ("EMIOENET0PTPDELAYREQRX",      1,  "output"),
        ("EMIOENET0PTPDELAYREQTX",      1,  "output"),
        ("EMIOENET0PTPPDELAYREQRX",     1,  "output"),
        ("EMIOENET0PTPPDELAYREQTX",     1,  "output"),
        ("EMIOENET0PTPPDELAYRESPRX",    1,  "output"),
        ("EMIOENET0PTPPDELAYRESPTX",    1,  "output"),
        ("EMIOENET0PTPSYNCFRAMERX",     1,  "output"),
        ("EMIOENET0PTPSYNCFRAMETX",     1,  "output"),
        ("EMIOENET0SOFRX",              1,  "output"),
        ("EMIOENET0SOFTX",              1,  "output"),
        ("EMIOENET1GMIITXD",            8,  "output"),
        ("EMIOENET1GMIITXEN",           1,  "output"),
        ("EMIOENET1GMIITXER",           1,  "output"),
        ("EMIOENET1MDIOMDC",            1,  "output"),
        ("EMIOENET1MDIOO",              1,  "output"),
        ("EMIOENET1MDIOTN",             1,  "output"),
        ("EMIOENET1PTPDELAYREQRX",      1,  "output"),
        ("EMIOENET1PTPDELAYREQTX",      1,  "output"),
        ("EMIOENET1PTPPDELAYREQRX",     1,  "output"),
        ("EMIOENET1PTPPDELAYREQTX",     1,  "output"),
        ("EMIOENET1PTPPDELAYRESPRX",    1,  "output"),
        ("EMIOENET1PTPPDELAYRESPTX",    1,  "output"),
        ("EMIOENET1PTPSYNCFRAMERX",     1,  "output"),
        ("EMIOENET1PTPSYNCFRAMETX",     1,  "output"),
        ("EMIOENET1SOFRX",              1,  "output"),
        ("EMIOENET1SOFTX",              1,  "output"),
        ("EMIOGPIOO",                   64, "output"),
        ("EMIOGPIOTN",                  64, "output"),
        ("EMIOI2C0SCLO",                1,  "output"),
        ("EMIOI2C0SCLTN",               1,  "output"),
        ("EMIOI2C0SDAO",                1,  "output"),
        ("EMIOI2C0SDATN",               1,  "output"),
        ("EMIOI2C1SCLO",                1,  "output"),
        ("EMIOI2C1SCLTN",               1,  "output"),
        ("EMIOI2C1SDAO",                1,  "output"),
        ("EMIOI2C1SDATN",               1,  "output"),
        ("EMIOPJTAGTDO",                1,  "output"),
        ("EMIOPJTAGTDTN",               1,  "output"),
        ("EMIOSDIO0BUSPOW",             1,  "output"),
        ("EMIOSDIO0BUSVOLT",            3,  "output"),
        ("EMIOSDIO0CLK",                1,  "output"),
        ("EMIOSDIO0CMDO",               1,  "output"),
        ("EMIOSDIO0CMDTN",              1,  "output"),
        ("EMIOSDIO0DATAO",              4,  "output"),
        ("EMIOSDIO0DATATN",             4,  "output"),
        ("EMIOSDIO0LED",                1,  "output"),
        ("EMIOSDIO1BUSPOW",             1,  "output"),
        ("EMIOSDIO1BUSVOLT",            3,  "output"),
        ("EMIOSDIO1CLK",                1,  "output"),
        ("EMIOSDIO1CMDO",               1,  "output"),
        ("EMIOSDIO1CMDTN",              1,  "output"),
        ("EMIOSDIO1DATAO",              4,  "output"),
        ("EMIOSDIO1DATATN",             4,  "output"),
        ("EMIOSDIO1LED",                1,  "output"),
        ("EMIOSPI0MO",                  1,  "output"),
        ("EMIOSPI0MOTN",                1,  "output"),
        ("EMIOSPI0SCLKO",               1,  "output"),
        ("EMIOSPI0SCLKTN",              1,  "output"),
        ("EMIOSPI0SO",                  1,  "output"),
        ("EMIOSPI0SSNTN",               1,  "output"),
        ("EMIOSPI0SSON",                3,  "output"),
        ("EMIOSPI0STN",                 1,  "output"),
        ("EMIOSPI1MO",                  1,  "output"),
        ("EMIOSPI1MOTN",                1,  "output"),
        ("EMIOSPI1SCLKO",               1,  "output"),
        ("EMIOSPI1SCLKTN",              1,  "output"),
        ("EMIOSPI1SO",                  1,  "output"),
        ("EMIOSPI1SSNTN",               1,  "output"),
        ("EMIOSPI1SSON",                3,  "output"),
        ("EMIOSPI1STN",                 1,  "output"),
        ("EMIOTRACECTL",                1,  "output"),
        ("EMIOTRACEDATA",               32, "output"),
        ("EMIOTTC0WAVEO",               3,  "output"),
        ("EMIOTTC1WAVEO",               3,  "output"),
        ("EMIOUART0DTRN",               1,  "output"),
        ("EMIOUART0RTSN",               1,  "output"),
        ("EMIOUART0TX",                 1,  "output"),
        ("EMIOUART1DTRN",               1,  "output"),
        ("EMIOUART1RTSN",               1,  "output"),
        ("EMIOUART1TX",                 1,  "output"),
        ("EMIOUSB0PORTINDCTL",          2,  "output"),
        ("EMIOUSB0VBUSPWRSELECT",       1,  "output"),
        ("EMIOUSB1PORTINDCTL",          2,  "output"),
        ("EMIOUSB1VBUSPWRSELECT",       1,  "output"),
        ("EMIOWDTRSTO",                 1,  "output"),
        ("EVENTEVENTO",                 1,  "output"),
        ("EVENTSTANDBYWFE",             2,  "output"),
        ("EVENTSTANDBYWFI",             2,  "output"),
        ("FCLKCLK",                     4,  "output"),
        ("FCLKRESETN",                  4,  "output"),
        ("FTMTF2PTRIGACK",              4,  "output"),
        ("FTMTP2FDEBUG",                32, "output"),
        ("FTMTP2FTRIG",                 4,  "output"),
        ("IRQP2F",                      29, "output"),
        ("MAXIGP0ARADDR",               32, "output"),
        ("MAXIGP0ARBURST",              2,  "output"),
        ("MAXIGP0ARCACHE",              4,  "output"),
        ("MAXIGP0ARESETN",              1,  "output"),
        ("MAXIGP0ARID",                 12, "output"),
        ("MAXIGP0ARLEN",                4,  "output"),
        ("MAXIGP0ARLOCK",               2,  "output"),
        ("MAXIGP0ARPROT",               3,  "output"),
        ("MAXIGP0ARQOS",                4,  "output"),
        ("MAXIGP0ARSIZE",               2,  "output"),
        ("MAXIGP0ARVALID",              1,  "output"),
        ("MAXIGP0AWADDR",               32, "output"),
        ("MAXIGP0AWBURST",              2,  "output"),
        ("MAXIGP0AWCACHE",              4,  "output"),
        ("MAXIGP0AWID",                 12, "output"),
        ("MAXIGP0AWLEN",                4,  "output"),
        ("MAXIGP0AWLOCK",               2,  "output"),
        ("MAXIGP0AWPROT",               3,  "output"),
        ("MAXIGP0AWQOS",                4,  "output"),
        ("MAXIGP0AWSIZE",               2,  "output"),
        ("MAXIGP0AWVALID",              1,  "output"),
        ("MAXIGP0BREADY",               1,  "output"),
        ("MAXIGP0RREADY",               1,  "output"),
        ("MAXIGP0WDATA",                32, "output"),
        ("MAXIGP0WID",                  12, "output"),
        ("MAXIGP0WLAST",                1,  "output"),
        ("MAXIGP0WSTRB",                4,  "output"),
        ("MAXIGP0WVALID",               1,  "output"),
        ("MAXIGP1ARADDR",               32, "output"),
        ("MAXIGP1ARBURST",              2,  "output"),
        ("MAXIGP1ARCACHE",              4,  "output"),
        ("MAXIGP1ARESETN",              1,  "output"),
        ("MAXIGP1ARID",                 12, "output"),
        ("MAXIGP1ARLEN",                4,  "output"),
        ("MAXIGP1ARLOCK",               2,  "output"),
        ("MAXIGP1ARPROT",               3,  "output"),
        ("MAXIGP1ARQOS",                4,  "output"),
        ("MAXIGP1ARSIZE",               2,  "output"),
        ("MAXIGP1ARVALID",              1,  "output"),
        ("MAXIGP1AWADDR",               32, "output"),
        ("MAXIGP1AWBURST",              2,  "output"),
        ("MAXIGP1AWCACHE",              4,  "output"),
        ("MAXIGP1AWID",                 12, "output"),
        ("MAXIGP1AWLEN",                4,  "output"),
        ("MAXIGP1AWLOCK",               2,  "output"),
        ("MAXIGP1AWPROT",               3,  "output"),
        ("MAXIGP1AWQOS",                4,  "output"),
        ("MAXIGP1AWSIZE",               2,  "output"),
        ("MAXIGP1AWVALID",              1,  "output"),
        ("MAXIGP1BREADY",               1,  "output"),
        ("MAXIGP1RREADY",               1,  "output"),
        ("MAXIGP1WDATA",                32, "output"),
        ("MAXIGP1WID",                  12, "output"),
        ("MAXIGP1WLAST",                1,  "output"),
        ("MAXIGP1WSTRB",                4,  "output"),
        ("MAXIGP1WVALID",               1,  "output"),
        ("SAXIACPARESETN",              1,  "output"),
        ("SAXIACPARREADY",              1,  "output"),
        ("SAXIACPAWREADY",              1,  "output"),
        ("SAXIACPBID",                  3,  "output"),
        ("SAXIACPBRESP",                2,  "output"),
        ("SAXIACPBVALID",               1,  "output"),
        ("SAXIACPRDATA",                64, "output"),
        ("SAXIACPRID",                  3,  "output"),
        ("SAXIACPRLAST",                1,  "output"),
        ("SAXIACPRRESP",                2,  "output"),
        ("SAXIACPRVALID",               1,  "output"),
        ("SAXIACPWREADY",               1,  "output"),
        ("SAXIGP0ARESETN",              1,  "output"),
        ("SAXIGP0ARREADY",              1,  "output"),
        ("SAXIGP0AWREADY",              1,  "output"),
        ("SAXIGP0BID",                  6,  "output"),
        ("SAXIGP0BRESP",                2,  "output"),
        ("SAXIGP0BVALID",               1,  "output"),
        ("SAXIGP0RDATA",                32, "output"),
        ("SAXIGP0RID",                  6,  "output"),
        ("SAXIGP0RLAST",                1,  "output"),
        ("SAXIGP0RRESP",                2,  "output"),
        ("SAXIGP0RVALID",               1,  "output"),
        ("SAXIGP0WREADY",               1,  "output"),
        ("SAXIGP1ARESETN",              1,  "output"),
        ("SAXIGP1ARREADY",              1,  "output"),
        ("SAXIGP1AWREADY",              1,  "output"),
        ("SAXIGP1BID",                  6,  "output"),
        ("SAXIGP1BRESP",                2,  "output"),
        ("SAXIGP1BVALID",               1,  "output"),
        ("SAXIGP1RDATA",                32, "output"),
        ("SAXIGP1RID",                  6,  "output"),
        ("SAXIGP1RLAST",                1,  "output"),
        ("SAXIGP1RRESP",                2,  "output"),
        ("SAXIGP1RVALID",               1,  "output"),
        ("SAXIGP1WREADY",               1,  "output"),
        ("SAXIHP0ARESETN",              1,  "output"),
        ("SAXIHP0ARREADY",              1,  "output"),
        ("SAXIHP0AWREADY",              1,  "output"),
        ("SAXIHP0BID",                  6,  "output"),
        ("SAXIHP0BRESP",                2,  "output"),
        ("SAXIHP0BVALID",               1,  "output"),
        ("SAXIHP0RACOUNT",              3,  "output"),
        ("SAXIHP0RCOUNT",               8,  "output"),
        ("SAXIHP0RDATA",                64, "output"),
        ("SAXIHP0RID",                  6,  "output"),
        ("SAXIHP0RLAST",                1,  "output"),
        ("SAXIHP0RRESP",                2,  "output"),
        ("SAXIHP0RVALID",               1,  "output"),
        ("SAXIHP0WACOUNT",              6,  "output"),
        ("SAXIHP0WCOUNT",               8,  "output"),
        ("SAXIHP0WREADY",               1,  "output"),
        ("SAXIHP1ARESETN",              1,  "output"),
        ("SAXIHP1ARREADY",              1,  "output"),
        ("SAXIHP1AWREADY",              1,  "output"),
        ("SAXIHP1BID",                  6,  "output"),
        ("SAXIHP1BRESP",                2,  "output"),
        ("SAXIHP1BVALID",               1,  "output"),
        ("SAXIHP1RACOUNT",              3,  "output"),
        ("SAXIHP1RCOUNT",               8,  "output"),
        ("SAXIHP1RDATA",                64, "output"),
        ("SAXIHP1RID",                  6,  "output"),
        ("SAXIHP1RLAST",                1,  "output"),
        ("SAXIHP1RRESP",                2,  "output"),
        ("SAXIHP1RVALID",               1,  "output"),
        ("SAXIHP1WACOUNT",              6,  "output"),
        ("SAXIHP1WCOUNT",               8,  "output"),
        ("SAXIHP1WREADY",               1,  "output"),
        ("SAXIHP2ARESETN",              1,  "output"),
        ("SAXIHP2ARREADY",              1,  "output"),
        ("SAXIHP2AWREADY",              1,  "output"),
        ("SAXIHP2BID",                  6,  "output"),
        ("SAXIHP2BRESP",                2,  "output"),
        ("SAXIHP2BVALID",               1,  "output"),
        ("SAXIHP2RACOUNT",              3,  "output"),
        ("SAXIHP2RCOUNT",               8,  "output"),
        ("SAXIHP2RDATA",                64, "output"),
        ("SAXIHP2RID",                  6,  "output"),
        ("SAXIHP2RLAST",                1,  "output"),
        ("SAXIHP2RRESP",                2,  "output"),
        ("SAXIHP2RVALID",               1,  "output"),
        ("SAXIHP2WACOUNT",              6,  "output"),
        ("SAXIHP2WCOUNT",               8,  "output"),
        ("SAXIHP2WREADY",               1,  "output"),
        ("SAXIHP3ARESETN",              1,  "output"),
        ("SAXIHP3ARREADY",              1,  "output"),
        ("SAXIHP3AWREADY",              1,  "output"),
        ("SAXIHP3BID",                  6,  "output"),
        ("SAXIHP3BRESP",                2,  "output"),
        ("SAXIHP3BVALID",               1,  "output"),
        ("SAXIHP3RACOUNT",              3,  "output"),
        ("SAXIHP3RCOUNT",               8,  "output"),
        ("SAXIHP3RDATA",                64, "output"),
        ("SAXIHP3RID",                  6,  "output"),
        ("SAXIHP3RLAST",                1,  "output"),
        ("SAXIHP3RRESP",                2,  "output"),
        ("SAXIHP3RVALID",               1,  "output"),
        ("SAXIHP3WACOUNT",              6,  "output"),
        ("SAXIHP3WCOUNT",               8,  "output"),
        ("SAXIHP3WREADY",               1,  "output"),
        ("DDRA",                        15, "inout" ),
        ("DDRBA",                       3,  "inout" ),
        ("DDRCASB",                     1,  "inout" ),
        ("DDRCKE",                      1,  "inout" ),
        ("DDRCKN",                      1,  "inout" ),
        ("DDRCKP",                      1,  "inout" ),
        ("DDRCSB",                      1,  "inout" ),
        ("DDRDM",                       4,  "inout" ),
        ("DDRDQ",                       32, "inout" ),
        ("DDRDQSN",                     4,  "inout" ),
        ("DDRDQSP",                     4,  "inout" ),
        ("DDRDRSTB",                    1,  "inout" ),
        ("DDRODT",                      1,  "inout" ),
        ("DDRRASB",                     1,  "inout" ),
        ("DDRVRN",                      1,  "inout" ),
        ("DDRVRP",                      1,  "inout" ),
        ("DDRWEB",                      1,  "inout" ),
        ("MIO",                         54, "inout" ),
        ("PSCLK",                       1,  "inout" ),
        ("PSPORB",                      1,  "inout" ),
        ("PSSRSTB",                     1,  "inout" ),
        ("DDRARB",                      4,  "input" ),
        ("DMA0ACLK",                    1,  "input" ),
        ("DMA0DAREADY",                 1,  "input" ),
        ("DMA0DRLAST",                  1,  "input" ),
        ("DMA0DRTYPE",                  2,  "input" ),
        ("DMA0DRVALID",                 1,  "input" ),
        ("DMA1ACLK",                    1,  "input" ),
        ("DMA1DAREADY",                 1,  "input" ),
        ("DMA1DRLAST",                  1,  "input" ),
        ("DMA1DRTYPE",                  2,  "input" ),
        ("DMA1DRVALID",                 1,  "input" ),
        ("DMA2ACLK",                    1,  "input" ),
        ("DMA2DAREADY",                 1,  "input" ),
        ("DMA2DRLAST",                  1,  "input" ),
        ("DMA2DRTYPE",                  2,  "input" ),
        ("DMA2DRVALID",                 1,  "input" ),
        ("DMA3ACLK",                    1,  "input" ),
        ("DMA3DAREADY",                 1,  "input" ),
        ("DMA3DRLAST",                  1,  "input" ),
        ("DMA3DRTYPE",                  2,  "input" ),
        ("DMA3DRVALID",                 1,  "input" ),
        ("EMIOCAN0PHYRX",               1,  "input" ),
        ("EMIOCAN1PHYRX",               1,  "input" ),
        ("EMIOENET0EXTINTIN",           1,  "input" ),
        ("EMIOENET0GMIICOL",            1,  "input" ),
        ("EMIOENET0GMIICRS",            1,  "input" ),
        ("EMIOENET0GMIIRXCLK",          1,  "input" ),
        ("EMIOENET0GMIIRXD",            8,  "input" ),
        ("EMIOENET0GMIIRXDV",           1,  "input" ),
        ("EMIOENET0GMIIRXER",           1,  "input" ),
        ("EMIOENET0GMIITXCLK",          1,  "input" ),
        ("EMIOENET0MDIOI",              1,  "input" ),
        ("EMIOENET1EXTINTIN",           1,  "input" ),
        ("EMIOENET1GMIICOL",            1,  "input" ),
        ("EMIOENET1GMIICRS",            1,  "input" ),
        ("EMIOENET1GMIIRXCLK",          1,  "input" ),
        ("EMIOENET1GMIIRXD",            8,  "input" ),
        ("EMIOENET1GMIIRXDV",           1,  "input" ),
        ("EMIOENET1GMIIRXER",           1,  "input" ),
        ("EMIOENET1GMIITXCLK",          1,  "input" ),
        ("EMIOENET1MDIOI",              1,  "input" ),
        ("EMIOGPIOI",                   64, "input" ),
        ("EMIOI2C0SCLI",                1,  "input" ),
        ("EMIOI2C0SDAI",                1,  "input" ),
        ("EMIOI2C1SCLI",                1,  "input" ),
        ("EMIOI2C1SDAI",                1,  "input" ),
        ("EMIOPJTAGTCK",                1,  "input" ),
        ("EMIOPJTAGTDI",                1,  "input" ),
        ("EMIOPJTAGTMS",                1,  "input" ),
        ("EMIOSDIO0CDN",                1,  "input" ),
        ("EMIOSDIO0CLKFB",              1,  "input" ),
        ("EMIOSDIO0CMDI",               1,  "input" ),
        ("EMIOSDIO0DATAI",              4,  "input" ),
        ("EMIOSDIO0WP",                 1,  "input" ),
        ("EMIOSDIO1CDN",                1,  "input" ),
        ("EMIOSDIO1CLKFB",              1,  "input" ),
        ("EMIOSDIO1CMDI",               1,  "input" ),
        ("EMIOSDIO1DATAI",              4,  "input" ),
        ("EMIOSDIO1WP",                 1,  "input" ),
        ("EMIOSPI0MI",                  1,  "input" ),
        ("EMIOSPI0SCLKI",               1,  "input" ),
        ("EMIOSPI0SI",                  1,  "input" ),
        ("EMIOSPI0SSIN",                1,  "input" ),
        ("EMIOSPI1MI",                  1,  "input" ),
        ("EMIOSPI1SCLKI",               1,  "input" ),
        ("EMIOSPI1SI",                  1,  "input" ),
        ("EMIOSPI1SSIN",                1,  "input" ),
        ("EMIOSRAMINTIN",               1,  "input" ),
        ("EMIOTRACECLK",                1,  "input" ),
        ("EMIOTTC0CLKI",                3,  "input" ),
        ("EMIOTTC1CLKI",                3,  "input" ),
        ("EMIOUART0CTSN",               1,  "input" ),
        ("EMIOUART0DCDN",               1,  "input" ),
        ("EMIOUART0DSRN",               1,  "input" ),
        ("EMIOUART0RIN",                1,  "input" ),
        ("EMIOUART0RX",                 1,  "input" ),
        ("EMIOUART1CTSN",               1,  "input" ),
        ("EMIOUART1DCDN",               1,  "input" ),
        ("EMIOUART1DSRN",               1,  "input" ),
        ("EMIOUART1RIN",                1,  "input" ),
        ("EMIOUART1RX",                 1,  "input" ),
        ("EMIOUSB0VBUSPWRFAULT",        1,  "input" ),
        ("EMIOUSB1VBUSPWRFAULT",        1,  "input" ),
        ("EMIOWDTCLKI",                 1,  "input" ),
        ("EVENTEVENTI",                 1,  "input" ),
        ("FCLKCLKTRIGN",                4,  "input" ),
        ("FPGAIDLEN",                   1,  "input" ),
        ("FTMDTRACEINATID",             4,  "input" ),
        ("FTMDTRACEINCLOCK",            1,  "input" ),
        ("FTMDTRACEINDATA",             32, "input" ),
        ("FTMDTRACEINVALID",            1,  "input" ),
        ("FTMTF2PDEBUG",                32, "input" ),
        ("FTMTF2PTRIG",                 4,  "input" ),
        ("FTMTP2FTRIGACK",              4,  "input" ),
        ("IRQF2P",                      20, "input" ),
        ("MAXIGP0ACLK",                 1,  "input" ),
        ("MAXIGP0ARREADY",              1,  "input" ),
        ("MAXIGP0AWREADY",              1,  "input" ),
        ("MAXIGP0BID",                  12, "input" ),
        ("MAXIGP0BRESP",                2,  "input" ),
        ("MAXIGP0BVALID",               1,  "input" ),
        ("MAXIGP0RDATA",                32, "input" ),
        ("MAXIGP0RID",                  12, "input" ),
        ("MAXIGP0RLAST",                1,  "input" ),
        ("MAXIGP0RRESP",                2,  "input" ),
        ("MAXIGP0RVALID",               1,  "input" ),
        ("MAXIGP0WREADY",               1,  "input" ),
        ("MAXIGP1ACLK",                 1,  "input" ),
        ("MAXIGP1ARREADY",              1,  "input" ),
        ("MAXIGP1AWREADY",              1,  "input" ),
        ("MAXIGP1BID",                  5,  "input" ),
        ("MAXIGP1BRESP",                2,  "input" ),
        ("MAXIGP1BVALID",               1,  "input" ),
        ("MAXIGP1RDATA",                32, "input" ),
        ("MAXIGP1RID",                  12, "input" ),
        ("MAXIGP1RLAST",                1,  "input" ),
        ("MAXIGP1RRESP",                2,  "input" ),
        ("MAXIGP1RVALID",               1,  "input" ),
        ("MAXIGP1WREADY",               1,  "input" ),
        ("SAXIACPACLK",                 1,  "input" ),
        ("SAXIACPARADDR",               32, "input" ),
        ("SAXIACPARBURST",              2,  "input" ),
        ("SAXIACPARCACHE",              4,  "input" ),
        ("SAXIACPARID",                 3,  "input" ),
        ("SAXIACPARLEN",                4,  "input" ),
        ("SAXIACPARLOCK",               2,  "input" ),
        ("SAXIACPARPROT",               3,  "input" ),
        ("SAXIACPARQOS",                4,  "input" ),
        ("SAXIACPARSIZE",               2,  "input" ),
        ("SAXIACPARUSER",               5,  "input" ),
        ("SAXIACPARVALID",              1,  "input" ),
        ("SAXIACPAWADDR",               32, "input" ),
        ("SAXIACPAWBURST",              2,  "input" ),
        ("SAXIACPAWCACHE",              4,  "input" ),
        ("SAXIACPAWID",                 3,  "input" ),
        ("SAXIACPAWLEN",                4,  "input" ),
        ("SAXIACPAWLOCK",               2,  "input" ),
        ("SAXIACPAWPROT",               3,  "input" ),
        ("SAXIACPAWQOS",                4,  "input" ),
        ("SAXIACPAWSIZE",               2,  "input" ),
        ("SAXIACPAWUSER",               5,  "input" ),
        ("SAXIACPAWVALID",              1,  "input" ),
        ("SAXIACPBREADY",               1,  "input" ),
        ("SAXIACPRREADY",               1,  "input" ),
        ("SAXIACPWDATA",                64, "input" ),
        ("SAXIACPWID",                  3,  "input" ),
        ("SAXIACPWLAST",                1,  "input" ),
        ("SAXIACPWSTRB",                8,  "input" ),
        ("SAXIACPWVALID",               1,  "input" ),
        ("SAXIGP0ACLK",                 1,  "input" ),
        ("SAXIGP0ARADDR",               32, "input" ),
        ("SAXIGP0ARBURST",              2,  "input" ),
        ("SAXIGP0ARCACHE",              4,  "input" ),
        ("SAXIGP0ARID",                 6,  "input" ),
        ("SAXIGP0ARLEN",                4,  "input" ),
        ("SAXIGP0ARLOCK",               2,  "input" ),
        ("SAXIGP0ARPROT",               3,  "input" ),
        ("SAXIGP0ARQOS",                4,  "input" ),
        ("SAXIGP0ARSIZE",               2,  "input" ),
        ("SAXIGP0ARVALID",              1,  "input" ),
        ("SAXIGP0AWADDR",               32, "input" ),
        ("SAXIGP0AWBURST",              2,  "input" ),
        ("SAXIGP0AWCACHE",              4,  "input" ),
        ("SAXIGP0AWID",                 6,  "input" ),
        ("SAXIGP0AWLEN",                4,  "input" ),
        ("SAXIGP0AWLOCK",               2,  "input" ),
        ("SAXIGP0AWPROT",               3,  "input" ),
        ("SAXIGP0AWQOS",                4,  "input" ),
        ("SAXIGP0AWSIZE",               2,  "input" ),
        ("SAXIGP0AWVALID",              1,  "input" ),
        ("SAXIGP0BREADY",               1,  "input" ),
        ("SAXIGP0RREADY",               1,  "input" ),
        ("SAXIGP0WDATA",                32, "input" ),
        ("SAXIGP0WID",                  6,  "input" ),
        ("SAXIGP0WLAST",                1,  "input" ),
        ("SAXIGP0WSTRB",                4,  "input" ),
        ("SAXIGP0WVALID",               1,  "input" ),
        ("SAXIGP1ACLK",                 1,  "input" ),
        ("SAXIGP1ARADDR",               32, "input" ),
        ("SAXIGP1ARBURST",              2,  "input" ),
        ("SAXIGP1ARCACHE",              4,  "input" ),
        ("SAXIGP1ARID",                 6,  "input" ),
        ("SAXIGP1ARLEN",                4,  "input" ),
        ("SAXIGP1ARLOCK",               2,  "input" ),
        ("SAXIGP1ARPROT",               3,  "input" ),
        ("SAXIGP1ARQOS",                4,  "input" ),
        ("SAXIGP1ARSIZE",               2,  "input" ),
        ("SAXIGP1ARVALID",              1,  "input" ),
        ("SAXIGP1AWADDR",               32, "input" ),
        ("SAXIGP1AWBURST",              2,  "input" ),
        ("SAXIGP1AWCACHE",              4,  "input" ),
        ("SAXIGP1AWID",                 6,  "input" ),
        ("SAXIGP1AWLEN",                4,  "input" ),
        ("SAXIGP1AWLOCK",               2,  "input" ),
        ("SAXIGP1AWPROT",               3,  "input" ),
        ("SAXIGP1AWQOS",                4,  "input" ),
        ("SAXIGP1AWSIZE",               2,  "input" ),
        ("SAXIGP1AWVALID",              1,  "input" ),
        ("SAXIGP1BREADY",               1,  "input" ),
        ("SAXIGP1RREADY",               1,  "input" ),
        ("SAXIGP1WDATA",                32, "input" ),
        ("SAXIGP1WID",                  6,  "input" ),
        ("SAXIGP1WLAST",                1,  "input" ),
        ("SAXIGP1WSTRB",                4,  "input" ),
        ("SAXIGP1WVALID",               1,  "input" ),
        ("SAXIHP0ACLK",                 1,  "input" ),
        ("SAXIHP0ARADDR",               32, "input" ),
        ("SAXIHP0ARBURST",              2,  "input" ),
        ("SAXIHP0ARCACHE",              4,  "input" ),
        ("SAXIHP0ARID",                 6,  "input" ),
        ("SAXIHP0ARLEN",                4,  "input" ),
        ("SAXIHP0ARLOCK",               2,  "input" ),
        ("SAXIHP0ARPROT",               3,  "input" ),
        ("SAXIHP0ARQOS",                4,  "input" ),
        ("SAXIHP0ARSIZE",               2,  "input" ),
        ("SAXIHP0ARVALID",              1,  "input" ),
        ("SAXIHP0AWADDR",               32, "input" ),
        ("SAXIHP0AWBURST",              2,  "input" ),
        ("SAXIHP0AWCACHE",              4,  "input" ),
        ("SAXIHP0AWID",                 6,  "input" ),
        ("SAXIHP0AWLEN",                4,  "input" ),
        ("SAXIHP0AWLOCK",               2,  "input" ),
        ("SAXIHP0AWPROT",               3,  "input" ),
        ("SAXIHP0AWQOS",                4,  "input" ),
        ("SAXIHP0AWSIZE",               2,  "input" ),
        ("SAXIHP0AWVALID",              1,  "input" ),
        ("SAXIHP0BREADY",               1,  "input" ),
        ("SAXIHP0RDISSUECAP1EN",        1,  "input" ),
        ("SAXIHP0RREADY",               1,  "input" ),
        ("SAXIHP0WDATA",                64, "input" ),
        ("SAXIHP0WID",                  6,  "input" ),
        ("SAXIHP0WLAST",                1,  "input" ),
        ("SAXIHP0WRISSUECAP1EN",        1,  "input" ),
        ("SAXIHP0WSTRB",                8,  "input" ),
        ("SAXIHP0WVALID",               1,  "input" ),
        ("SAXIHP1ACLK",                 1,  "input" ),
        ("SAXIHP1ARADDR",               32, "input" ),
        ("SAXIHP1ARBURST",              2,  "input" ),
        ("SAXIHP1ARCACHE",              4,  "input" ),
        ("SAXIHP1ARID",                 6,  "input" ),
        ("SAXIHP1ARLEN",                4,  "input" ),
        ("SAXIHP1ARLOCK",               2,  "input" ),
        ("SAXIHP1ARPROT",               3,  "input" ),
        ("SAXIHP1ARQOS",                4,  "input" ),
        ("SAXIHP1ARSIZE",               2,  "input" ),
        ("SAXIHP1ARVALID",              1,  "input" ),
        ("SAXIHP1AWADDR",               32, "input" ),
        ("SAXIHP1AWBURST",              2,  "input" ),
        ("SAXIHP1AWCACHE",              4,  "input" ),
        ("SAXIHP1AWID",                 6,  "input" ),
        ("SAXIHP1AWLEN",                4,  "input" ),
        ("SAXIHP1AWLOCK",               2,  "input" ),
        ("SAXIHP1AWPROT",               3,  "input" ),
        ("SAXIHP1AWQOS",                4,  "input" ),
        ("SAXIHP1AWSIZE",               2,  "input" ),
        ("SAXIHP1AWVALID",              1,  "input" ),
        ("SAXIHP1BREADY",               1,  "input" ),
        ("SAXIHP1RDISSUECAP1EN",        1,  "input" ),
        ("SAXIHP1RREADY",               1,  "input" ),
        ("SAXIHP1WDATA",                64, "input" ),
        ("SAXIHP1WID",                  6,  "input" ),
        ("SAXIHP1WLAST",                1,  "input" ),
        ("SAXIHP1WRISSUECAP1EN",        1,  "input" ),
        ("SAXIHP1WSTRB",                8,  "input" ),
        ("SAXIHP1WVALID",               1,  "input" ),
        ("SAXIHP2ACLK",                 1,  "input" ),
        ("SAXIHP2ARADDR",               32, "input" ),
        ("SAXIHP2ARBURST",              2,  "input" ),
        ("SAXIHP2ARCACHE",              4,  "input" ),
        ("SAXIHP2ARID",                 6,  "input" ),
        ("SAXIHP2ARLEN",                4,  "input" ),
        ("SAXIHP2ARLOCK",               2,  "input" ),
        ("SAXIHP2ARPROT",               3,  "input" ),
        ("SAXIHP2ARQOS",                4,  "input" ),
        ("SAXIHP2ARSIZE",               2,  "input" ),
        ("SAXIHP2ARVALID",              1,  "input" ),
        ("SAXIHP2AWADDR",               32, "input" ),
        ("SAXIHP2AWBURST",              2,  "input" ),
        ("SAXIHP2AWCACHE",              4,  "input" ),
        ("SAXIHP2AWID",                 6,  "input" ),
        ("SAXIHP2AWLEN",                4,  "input" ),
        ("SAXIHP2AWLOCK",               2,  "input" ),
        ("SAXIHP2AWPROT",               3,  "input" ),
        ("SAXIHP2AWQOS",                4,  "input" ),
        ("SAXIHP2AWSIZE",               2,  "input" ),
        ("SAXIHP2AWVALID",              1,  "input" ),
        ("SAXIHP2BREADY",               1,  "input" ),
        ("SAXIHP2RDISSUECAP1EN",        1,  "input" ),
        ("SAXIHP2RREADY",               1,  "input" ),
        ("SAXIHP2WDATA",                64, "input" ),
        ("SAXIHP2WID",                  6,  "input" ),
        ("SAXIHP2WLAST",                1,  "input" ),
        ("SAXIHP2WRISSUECAP1EN",        1,  "input" ),
        ("SAXIHP2WSTRB",                8,  "input" ),
        ("SAXIHP2WVALID",               1,  "input" ),
        ("SAXIHP3ACLK",                 1,  "input" ),
        ("SAXIHP3ARADDR",               32, "input" ),
        ("SAXIHP3ARBURST",              2,  "input" ),
        ("SAXIHP3ARCACHE",              4,  "input" ),
        ("SAXIHP3ARID",                 6,  "input" ),
        ("SAXIHP3ARLEN",                4,  "input" ),
        ("SAXIHP3ARLOCK",               2,  "input" ),
        ("SAXIHP3ARPROT",               3,  "input" ),
        ("SAXIHP3ARQOS",                4,  "input" ),
        ("SAXIHP3ARSIZE",               2,  "input" ),
        ("SAXIHP3ARVALID",              1,  "input" ),
        ("SAXIHP3AWADDR",               32, "input" ),
        ("SAXIHP3AWBURST",              2,  "input" ),
        ("SAXIHP3AWCACHE",              4,  "input" ),
        ("SAXIHP3AWID",                 6,  "input" ),
        ("SAXIHP3AWLEN",                4,  "input" ),
        ("SAXIHP3AWLOCK",               2,  "input" ),
        ("SAXIHP3AWPROT",               3,  "input" ),
        ("SAXIHP3AWQOS",                4,  "input" ),
        ("SAXIHP3AWSIZE",               2,  "input" ),
        ("SAXIHP3AWVALID",              1,  "input" ),
        ("SAXIHP3BREADY",               1,  "input" ),
        ("SAXIHP3RDISSUECAP1EN",        1,  "input" ),
        ("SAXIHP3RREADY",               1,  "input" ),
        ("SAXIHP3WDATA",                64, "input" ),
        ("SAXIHP3WID",                  6,  "input" ),
        ("SAXIHP3WLAST",                1,  "input" ),
        ("SAXIHP3WRISSUECAP1EN",        1,  "input" ),
        ("SAXIHP3WSTRB",                8,  "input" ),
        ("SAXIHP3WVALID",               1,  "input" ),
    ]

    return ports

def get_axi_layout(axi, data_w=None, addr_w=None, id_w=None):
    assert data_w is None or data_w % 8 == 0
    if axi == "master":
        if data_w is None:
            data_w = 128
        if addr_w is None:
            addr_w = 40
        if id_w is None:
            id_w = 16
        return [
            ("ARADDR", addr_w, "output"),
            ("ARBURST", 2, "output"),
            ("ARCACHE", 4, "output"),
            ("ARID", id_w, "output"),
            ("ARLEN", 8, "output"),
            ("ARLOCK", 1, "output"),
            ("ARPROT", 3, "output"),
            ("ARQOS", 4, "output"),
            ("ARSIZE", 3, "output"),
            ("ARUSER", 16, "output"),
            ("ARVALID", 1, "output"),
            ("AWADDR", addr_w, "output"),
            ("AWBURST", 2, "output"),
            ("AWCACHE", 4, "output"),
            ("AWID", id_w, "output"),
            ("AWLEN", 8, "output"),
            ("AWLOCK", 1, "output"),
            ("AWPROT", 3, "output"),
            ("AWQOS", 4, "output"),
            ("AWSIZE", 3, "output"),
            ("AWUSER", 16, "output"),
            ("AWVALID", 1, "output"),
            ("BREADY", 1, "output"),
            ("RREADY", 1, "output"),
            ("WDATA", data_w, "output"),
            ("WLAST", 1, "output"),
            ("WSTRB", data_w // 8, "output"),
            ("WVALID", 1, "output"),
            ("ACLK", 1, "input"),
            ("ARREADY", 1, "input"),
            ("AWREADY", 1, "input"),
            ("BID", id_w, "input"),
            ("BRESP", 2, "input"),
            ("BVALID", 1, "input"),
            ("RDATA", data_w, "input"),
            ("RID", id_w, "input"),
            ("RLAST", 1, "input"),
            ("RRESP", 2, "input"),
            ("RVALID", 1, "input"),
            ("WREADY", 1, "input"),
        ]
    if axi == "slave":
        if data_w is None:
            data_w = 128
        if addr_w is None:
            addr_w = 49
        if id_w is None:
            id_w = 6
        return [
            ("ARREADY", 1, "output"),
            ("AWREADY", 1, "output"),
            ("BID", id_w, "output"),
            ("BRESP", 2, "output"),
            ("BVALID", 1, "output"),
            ("RACOUNT", 4, "output"),
            ("RCOUNT", 8, "output"),
            ("RDATA", data_w, "output"),
            ("RID", id_w, "output"),
            ("RLAST", 1, "output"),
            ("RRESP", 2, "output"),
            ("RVALID", 1, "output"),
            ("WACOUNT", 4, "output"),
            ("WCOUNT", 8, "output"),
            ("WREADY", 1, "output"),
            ("ARADDR", addr_w, "input"),
            ("ARBURST", 2, "input"),
            ("ARCACHE", 4, "input"),
            ("ARID", id_w, "input"),
            ("ARLEN", 8, "input"),
            ("ARLOCK", 1, "input"),
            ("ARPROT", 3, "input"),
            ("ARQOS", 4, "input"),
            ("ARSIZE", 3, "input"),
            ("ARUSER", 1, "input"),
            ("ARVALID", 1, "input"),
            ("AWADDR", addr_w, "input"),
            ("AWBURST", 2, "input"),
            ("AWCACHE", 4, "input"),
            ("AWID", id_w, "input"),
            ("AWLEN", 8, "input"),
            ("AWLOCK", 1, "input"),
            ("AWPROT", 3, "input"),
            ("AWQOS", 4, "input"),
            ("AWSIZE", 3, "input"),
            ("AWUSER", 1, "input"),
            ("AWVALID", 1, "input"),
            ("BREADY", 1, "input"),
            ("RCLK", 1, "input"),
            ("RREADY", 1, "input"),
            ("WCLK", 1, "input"),
            ("WDATA", data_w, "input"),
            ("WLAST", 1, "input"),
            ("WSTRB", data_w // 8, "input"),
            ("WVALID", 1, "input"),
        ]
    if axi == "slave_acp":
        if data_w is None:
            data_w = 128
        if addr_w is None:
            addr_w = 40
        if id_w is None:
            id_w = 5
        return [
            ("ARREADY", 1, "output"),
            ("AWREADY", 1, "output"),
            ("BID", id_w, "output"),
            ("BRESP", 2, "output"),
            ("BVALID", 1, "output"),
            ("RDATA", data_w, "output"),
            ("RID", id_w, "output"),
            ("RLAST", 1, "output"),
            ("RRESP", 2, "output"),
            ("RVALID", 1, "output"),
            ("WREADY", 1, "output"),
            ("ACLK", 1, "input"),
            ("ARADDR", addr_w, "input"),
            ("ARBURST", 2, "input"),
            ("ARCACHE", 4, "input"),
            ("ARID", id_w, "input"),
            ("ARLEN", 8, "input"),
            ("ARLOCK", 1, "input"),
            ("ARPROT", 3, "input"),
            ("ARQOS", 4, "input"),
            ("ARSIZE", 3, "input"),
            ("ARUSER", 2, "input"),
            ("ARVALID", 1, "input"),
            ("AWADDR", addr_w, "input"),
            ("AWBURST", 2, "input"),
            ("AWCACHE", 4, "input"),
            ("AWID", id_w, "input"),
            ("AWLEN", 8, "input"),
            ("AWLOCK", 1, "input"),
            ("AWPROT", 3, "input"),
            ("AWQOS", 4, "input"),
            ("AWSIZE", 3, "input"),
            ("AWUSER", 2, "input"),
            ("AWVALID", 1, "input"),
            ("BREADY", 1, "input"),
            ("RREADY", 1, "input"),
            ("WDATA", data_w, "input"),
            ("WLAST", 1, "input"),
            ("WSTRB", data_w // 8, "input"),
            ("WVALID", 1, "input"),
        ]
    raise ValueError("Invalid axi interface")
